.github/workflows/ci.yml

There are a few of deprecated options that do not work anymore. See here https://github.com/google-github-actions/setup-gcloud#authentication-inputs
So this is updating to `google-github-actions/auth@v0`.

github/workflows: export google creds

---

cmd/calyptia/get_aggregator.go
cmd/calyptia/update_aggregator.go

rename instance to core_instance

---

k8s/labels.go

Add required extra labels.
LabelAggregatorName = "calyptia_aggregator_name"
LabelPipelineID     = "calyptia_pipeline_id"
LabelPipelineName   = "calyptia_pipeline_name"

Update extra labels

---

cmd/calyptia/delete_core_instance_k8s.go

Fixes confirm message in case have 0 things to delete and doest not show the message when in interactive mode

Fix delete message at core_instance

---

.github/workflows/ci.yml

- Run cloud-e2e tests on PR/New release.

Enable cloud-e2e tests

---

cmd/calyptia/client.go
cmd/calyptia/client_mock_gen.go
cmd/calyptia/create.go
cmd/calyptia/create_environment.go
cmd/calyptia/create_environment_test.go
cmd/calyptia/delete.go
cmd/calyptia/delete_environment.go
cmd/calyptia/delete_environment_test.go
cmd/calyptia/get.go
cmd/calyptia/get_environment.go
cmd/calyptia/update.go
cmd/calyptia/update_environment.go
cmd/calyptia/update_environment_test.go

Create a new environment at calyptia cloud

---

aws/client.go
aws/client_mock.go
cmd/calyptia/create_core_instance_aws.go
cmd/calyptia/delete_core_instance.go
cmd/calyptia/delete_core_instance_aws.go
cmd/calyptia/delete_core_instance_aws_test.go
go.mod
go.sum

Partially solves #106 
Created instances with
```shell
➜ cli (cli/issues/106/delete) ✗ ./calyptia create core_instance aws --profile=calyptia-cli --key-pair niedbalski-keys --name core-aws-delete --instance-type t2.xlarge --no-elastic-ip --environment prod
Creating calyptia core instance on AWS
calyptia core instance running on AWS instance-id: i-05d05bfba54e52bbc, instance-type: t2.xlarge, privateIPv4: 172.31.29.147
Calyptia core instance is ready to use.
➜ cli (cli/issues/106/delete) ✗ ./calyptia create core_instance aws --profile=calyptia-cli --key-pair niedbalski-keys --name core-aws-delete --instance-type t2.xlarge --no-elastic-ip --environment qa  
Creating calyptia core instance on AWS
calyptia core instance running on AWS …
```

Implement delete core_instance for AWS

---

.goreleaser.yml
README.md
cmd/calyptia/create.go
cmd/calyptia/delete.go
cmd/calyptia/update.go

Adding `brew` instructions to goreleaser.
Closes https://github.com/calyptia/cli/issues/138

goreleaser: brew

---

cmd/calyptia/create_core_instance_k8s_test.go
k8s/client.go

Follow up to https://github.com/calyptia/core/pull/213 

Add calyptia prefix to created objects

---

cmd/calyptia/delete_core_instance.go
cmd/calyptia/delete_core_instance_gcp.go
cmd/calyptia/delete_core_instance_gcp_test.go
gcp/client.go
gcp/client_mock.go

complements #107 with deletion of a GCP instance

Delete instance on GCP

---

gcp/config.go

nat ip field was not being omit when empty, causing a problem on deployment case the client wants an ephemeral ip (auto-generated)

Omit nat ip field case client wants ephemeral ip

---

gcp/client.go

It was being used `c.deploymentName` variable to hold the `operation.Name` information, now we have a `c.currentOperation` to hold this information that is used to follow the operation that is running on the moment.
This confusion _(caused by myself)_ made me delete de `c.deploymentName` for delete action and not save the current operation, making the delete operation wait in loop (without break it).

Fix operation name from delete operation

---

cmd/calyptia/client.go
cmd/calyptia/client_mock_gen.go
cmd/calyptia/create.go
cmd/calyptia/create_core_instance_k8s.go
cmd/calyptia/create_ingest_check.go
cmd/calyptia/delete.go
cmd/calyptia/delete_ingest_check.go
cmd/calyptia/get.go
cmd/calyptia/get_environment.go
cmd/calyptia/get_ingest_check.go
gcp/client_mock.go
go.sum

Add support for ingest checks cli side 1/2

---

cmd/calyptia/client_mock_gen.go
cmd/calyptia/config.go
cmd/calyptia/config_url.go
cmd/calyptia/create_core_instance_k8s.go
cmd/calyptia/create_ingest_check.go
cmd/calyptia/delete_ingest_check.go
cmd/calyptia/get_ingest_check.go
cmd/calyptia/main.go
gcp/client_mock.go
k8s/client.go

Create config set url option

---

.github/workflows/ci.yml

Signed-off-by: Patrick Stephens <pat@calyptia.com>

workflows: fix authentication

---

.github/workflows/ci.yml

Signed-off-by: Patrick Stephens <pat@calyptia.com>

workflows: remove cred file to prevent dirty git

---

cmd/calyptia/update_core_instance_k8s.go
k8s/client.go

Enable the no-tls-verify parameter to the core_instance update command.

Pass CORE_TLS_VERIFY to update core_instance k8s.

---

cmd/calyptia/get_pipeline_file.go

Closes https://github.com/calyptia/cli/issues/232

show file contents as string if not encrypted

---

.goreleaser.yml

- Enable linux/arm64 releases.

Enable releases on linux/arm64

---

cmd/calyptia/create_core_instance_k8s.go
go.sum
k8s/client.go

Allow to Also inject environment variable in the target core instance for CORE_INSTANCE_SKIP_SERVICE_CREATION.

Allow injecting environment variable for CORE_INSTANCE_SKIP_SERVICE_CREATION

---

aws/client.go
cmd/calyptia/get_cluster_objects.go
gcp/client.go

Fix panic due to an unhandled error.
Also addressed some other issues that potentially could cause a panic too due to nil pointers.

gcp: unhandled error

---

.github/workflows/lint.yml
go.mod
go.sum

Dep update

---

aws/client.go
cmd/calyptia/create_core_instance_aws.go
cmd/calyptia/create_core_instance_gcp.go
gcp/config.go

finish the work started on #284 and intends to fix the #286 issue 

Add the flag skip-servic-creation to the aws and gcp commands

---

completer/completer.go
helpers/helpers.go
slice/slice.go

added slice package

---

k8s/client.go

This is to help out with this PR:
https://github.com/calyptia/cloud/pull/844

adding pod namespace as environment variable in the container

---

cmd/delete.go
cmd/fleet/delete_fleet.go

Add the delete command for fleets.
Should be routine code. Actual integration tests are forthcoming.
Implemented while working on calyptia/cloud-e2e#72.

fleet: add delete command.

---

cmd/coreinstance/create_core_instance_operator.go
k8s/client.go

close calyptia/core-operator#111, calyptia/core-operator#113, calyptia/core-operator#110

Updates sync interval and get cluster information and version.

---

cmd/coreinstance/create_core_instance_operator.go
k8s/client.go

the kube config was fixed now uses the reccomended env from the library

Fix find current namespace to use recommended config path

---

.github/workflows/ci.yml

workflows: disable tests on release

---

cmd/coreinstance/create_core_instance_operator.go
cmd/operator/install.go
go.work.sum
k8s/client.go

eg
```shell
calyptia operator install operator --wait
customresourcedefinition.apiextensions.k8s.io/pipelines.core.calyptia.com created
serviceaccount/controller-manager created
clusterrole.rbac.authorization.k8s.io/manager-role created
clusterrole.rbac.authorization.k8s.io/metrics-reader created
clusterrole.rbac.authorization.k8s.io/proxy-role created
clusterrolebinding.rbac.authorization.k8s.io/manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/proxy-rolebinding created
service/controller-manager-metrics-service created
deployment.apps/controller-manager created
Waiting for core operator manager to be ready...
Core operator manager is ready. Took 11.0168455s
Core operator manager successfully installed.
```
*Disclaimer: Please do not create a Pull Request without …

Fix wait parameter for install core instance

---

.github/workflows/ci.yml
.goreleaser.yml

Remove deprecated options from build.

Remove deprecated options from build

---

.goreleaser.yml

Enable UPX compression for linux/window amd64/arm64

Add upx compression for linux/windows amd64/arm64.

---

k8s/client.go

Added additional check when waiting for deployment to come up
https://app.asana.com/0/1205296321537082/1205363711355050

additional check when waiting

---

.github/workflows/cron-release-check.yaml

Fix release tags and switch to core-operator-releases repo.

Fix release tags and switch to core-operator-releases repo.

---

cmd/utils/utils.go

Update version to v2.0.3 of operator

---

cmd/operator/install.go

Previous implementation was injecting default version into manifest.yaml. With this PR version tag will be injected only if --version value is passed in

using manifest.yaml as is

---

.github/workflows/ci.yml

Update core-product-release on release.
https://app.asana.com/0/1204881426070801/1205629387200107/f

workflows: push to core-product-release

---

cmd/fleet/create_fleet_file.go

Allow creating fleet files with extensions with the CLI.

fleet/files: allow file extensions for fleet files.

---

.github/workflows/ci.yml

Resolve issue during release with no Gcloud auth.

workflows: update auth for gcloud

---

install.sh

Failing when unable to fetch tag_name

fixing install.sh script

---

k8s/client.go

Setting correct RBAC for core instance

fixing core_instance RBAC

---

cmd/coreinstance/create_core_instance_operator.go
k8s/client.go

Adding annotations to core_instance opeator on create
https://app.asana.com/0/1204316201844829/1206049531392534
Needs https://github.com/calyptia/core-operator/pull/344

Core-Instance annotations

---

.github/workflows/ci.yml
k8s/client.go

Replaces e2e tests with vCluster option

feat: replace e2e tests with vCluster option

---

.github/workflows/call-update-core-operator-version.yaml
.github/workflows/ci.yml
.github/workflows/lint.yml
.goreleaser.yml
Dockerfile
install.sh

Part of work to handle Chronosphere migration

migration: update

---

.github/workflows/ci.yml

Resolves failures in release due to changes from https://github.com/chronosphereio/calyptia-cli/pull/778
Trivial revert of migration update to fix release: https://github.com/chronosphereio/calyptia-cli/actions/runs/8376127495/job/22935628793

workflows: fix homebrew release

---

LICENSE

Switch to Apache licence to allow usage in CICD, etc.
cc @agup006

Switch to Apache licence

---

cmd/coreinstance/create_core_instance_operator.go
k8s/client.go

In the previous commit I omitted passing namespace parameter to the rollback

Fixing rollback namespaces

---

.github/workflows/ci-install-script.yaml
.github/workflows/ci.yml
install.sh

Part of work to improve testing of CLI installation.
Resolved various problems found during testing, primarily with Windows installation.

[sc-94456]: workflows - add install script checks

---

.github/workflows/ci-install-script.yaml
.github/workflows/ci-update-pipelines.yaml
update-all-pipeline-images.sh

Simple script to automate the updating of all images used by every instance and pipeline. Primarily to improve the UX for any future changes around CVEs, etc.
CI tests added along with simple fix for install script rate limiting on CI too.

[sc-94681]: script to update all images

---

.github/workflows/ci-update-pipelines.yaml
go.mod
go.sum

term bump to 0.21.0 
Closes #867

term bump to 0.21.0
