chronosphereio/calyptia-cli

.gitignore
Getting:
```
git is currently in a dirty state
Please check in your pipeline what can be changing the following files:
?? gha-creds-8248dd7a92d546ae.json
```
right now. Here is an explanation of what is happening https://goreleaser.com/errors/dirty/
This PR just adds the file to `.gitignore`.
=> git: ignore google generated creds from ci

.gitignore, cmd/calyptia/create_aggregator_k8s.go, cmd/calyptia/create_aggregator_k8s_test.go, cmd/calyptia/k8s_client.go
- Create cluster secret from created aggregator RSA private key. This is subsequently
used by the calyptia-core instance to decode secrets.
=> Create cluster secret from RSA private key.

cmd/calyptia/create_aggregator_k8s.go, go.mod, pkg/k8s/client.go, pkg/k8s/labels.go
The k8s package should be exportable and usable across. We'll re-use
the labels definitions at core and possibly we can grow the client from this repository.
=> K8s labels in a package.

cmd/calyptia/get_core_instance.go, cmd/calyptia/get_core_instance_test.go, cmd/calyptia/utl.go, go.mod, go.sum
- Adds the --show-metadata parameter.
- Will filter out empty or zeroed variables.
Fixes #83
```
➜ cli (show-metadata) ✔ ./calyptia get core_instances --cloud-url http://localhost:5000  --show-metadata
NAME          VERSION  ENVIRONMENT PIPELINES TAGS STATUS      AGE     METADATA
core-instance v0.1-dev default     1              unreachable 6 hours {"k8s.cluster_platform":"linux/arm64","k8s.cluster_version":"1.21.1","k8s.namespace":"default"}
➜ cli (show-metadata) ✔ ./calyptia get core_instances --cloud-url http://localhost:5000                 
NAME          VERSION  ENVIRONMENT PIPELINES TAGS STATUS      AGE
core-instance v0.1-dev default     1              unreachable 6 hours
➜ cli (show-metadata) ✔ 
```
#83
=> Add --show-metadata to get core_instances.

aws/client.go, cmd/calyptia/create_core_instance_aws.go, cmd/calyptia/delete_core_instance_aws.go
Enable debug logging for AWS create/delete operations.
=>  Enable debug logging for AWS create/delete operations.

aws/client.go, cmd/calyptia/create_core_instance_aws.go, cmd/calyptia/create_core_instance_gcp.go, gcp/config.go
To use Google Cloud test images we need to inform the GITHUB_TOKEN on the creation, this PR enables it by allow the user pass this param thought the `CALYPTIA_GITHUB_TOKEN` environemnt, besides removes the flag `uses-test-image` from the cli user, and add the `CALYPTIA_TEST_IMAGE_ENABLE` making it not "cleary exposed" exposed to the user, once that just the develoment team will use it on e2e tests.
Reason behind this pr is that its was being showed to the user test flags, and it was needing anther flag for the github token, what doesnt make sense outside of dev team context, thats why we r moving it to env variables, to hide it from the user
=> Add on configs github token needed by test images

cmd/calyptia/create_core_instance_gcp.go, cmd/calyptia/delete_core_instance_gcp.go, gcp/client.go
Google API inst behaving same way in diferent environments, like CI or machine, it should get by default in any SO the `GOOGLE_APPLICATION_CREDENTIALS ` environement with the credentiasl, so we r adding the credentials as a parameter and passing it to the client as an option, if the client have it already set on the env it will get from there, if he inform we will consider the informed one.
Client return an error case there is no credentials
order that the client api searches for the auth: https://cloud.google.com/docs/authentication/application-default-credentials#search_order
=> Add credentials flag to gcp client

cmd/calyptia/create_core_instance_gcp.go, cmd/calyptia/delete_core_instance_gcp.go, gcp/client.go
During the e2e test [i caught a mistake while evaluating errors coming back from GCP](https://github.com/calyptia/cloud-e2e/actions/runs/3096039417/jobs/5011119422#step:11:252), so this purpose improves the error handling for operations that is happening on deployment manager.
=> Improve the error handling for Follow Operations method on GCP

cmd/calyptia/create_core_instance.go, cmd/calyptia/delete_core_instance.go, cmd/calyptia/delete_core_instance_aws.go, gcp/config.go
Remove `(TODO)` from already implemented function on `calyptia create/delete core_images` and small fix when is informed `latest` version for GCP images, `latest` is replacing the base image already defined in the `config.yaml`
=> Remove (TODO) from already implemented commands and fix on latest gcp image

cmd/calyptia/create_core_instance_k8s.go, cmd/calyptia/delete_core_instance_k8s.go, go.mod, k8s/client.go
Adds the operation to delete daemonSets by aggregator label from the cluster.
```
➜ cli (main) ✗ ./calyptia delete core_instance k8s cluster-logging                                
Are you sure you want to delete core instance with id "a5bfe07d-be4f-4d56-a0ee-d676064a75a8" and all of its associated kubernetes resources? (y/N) y
Successfully deleted core instance with id "a5bfe07d-be4f-4d56-a0ee-d676064a75a8"
DaemonSets:
namespace=default name=calyptia-cluster-logging-ec91
Deployments:
namespace=default name=calyptia-cluster-logging-default-deployment
namespace=default name=calyptia-health-check-b08c
Services:
namespace=default name=tcp-2020-9fb2933f-735a-4ac0-8194-5b87af15dc41
Service accounts:
namespace=default …
```
=> Delete daemonSets by label from cluster.

cmd/calyptia/main.go
Changing cobra default output to stdout. This fixes printing messages.
Before:
```
cmd.Printf    -> stderr
cmd.PrintErrf -> srderr
```
Now:
```
cmd.Printf    -> stdout
cmd.PrintErrf -> srderr
```
Specifically, this fixes the new Core docker-desktop extension which executes cli commands and asserts based on whether it wrote to stdout or stderr.
=> cmd/calyptia: set default output to stdout

cmd/calyptia/delete_core_instance_k8s.go, k8s/client.go
- Client isn't forcing the removal of labeled config maps.
- Force removal of config maps when a core_instance gets deleted. Discovered in a session with @edsiper.
N/A.
=> Enforce deletion of config maps on removal of core_instance.

cmd/calyptia/rollout_pipeline.go
Add flag to skip config validation on rollout, as reported by @agup006 
Fixes bug #258
=> [rollout] skip config validation.

cmd/calyptia/create_ingest_check.go, cmd/calyptia/create_pipeline.go, cmd/calyptia/create_pipeline_test.go, cmd/calyptia/create_resource_profile.go, cmd/calyptia/create_resource_profile_test.go, cmd/calyptia/delete_core_instance.go, cmd/calyptia/delete_core_instance_aws.go, cmd/calyptia/delete_core_instance_aws_test.go, cmd/calyptia/delete_core_instance_gcp.go, cmd/calyptia/delete_core_instance_k8s.go, cmd/calyptia/delete_environment.go, cmd/calyptia/delete_pipeline.go, cmd/calyptia/get.go, cmd/calyptia/get_core_instance.go, cmd/calyptia/get_core_instance_test.go, cmd/calyptia/get_ingest_check.go, cmd/calyptia/get_pipeline.go, cmd/calyptia/get_pipeline_test.go, cmd/calyptia/get_resource_profile.go, cmd/calyptia/get_resource_profile_test.go, cmd/calyptia/update_core_instance_aws.go, cmd/calyptia/update_core_instance_gcp.go, cmd/calyptia/update_core_instance_k8s.go
This is just a parameter rename, it doesn't takes cares of the client/API refactor to resort
everything to the core_instance nomenclature, that will come as part a renaming refactor previous
to release 1.0 on cloud.
For now, rename the parameters from --aggregator to --core_instance to make it consistent.
Fixes bug #252
=> Rename aggregator parameter to core_instance.

cmd/calyptia/create_ingest_check.go, cmd/calyptia/create_pipeline.go, cmd/calyptia/create_pipeline_test.go, cmd/calyptia/create_resource_profile.go, cmd/calyptia/create_resource_profile_test.go, cmd/calyptia/delete_core_instance_aws_test.go, cmd/calyptia/delete_ingest_check.go, cmd/calyptia/delete_pipeline.go, cmd/calyptia/get_ingest_check.go, cmd/calyptia/get_pipeline.go, cmd/calyptia/get_pipeline_test.go, cmd/calyptia/get_resource_profile.go, cmd/calyptia/get_resource_profile_test.go
* First level objects such as ingest_checks or core_instance should be underscored.
* Parameters should be - separated.
=> Set first level object names as underscore_name and parameters as hyphen separated.

k8s/client.go
Prevent "delete" methods on k8s client from returning error if the resource is not found.
Closes https://github.com/calyptia/cli/issues/275.
=> k8s: idempotent delete

cmd/calyptia/auth.go, cmd/calyptia/config_token.go, cmd/calyptia/config_url.go, cmd/calyptia/main.go, localdata/keyring.go, localdata/keyring_test.go
This PR intends to resolve #299 
Creates a package to be used to save small data.
The usability basically is `localData.Save(key, data)`, `localData.Get(key)`, `localData.Delete(key)`, it will try to save on the os keyring if its not available it will save on a local file like we were doing before, the refactor was around the usability and the code duplication, not around the functionality itself so it remains the same, just a bit **more reusable**, **documented** and with **tests**.
If it looks good for everyone it will be used on the #256 implementation also
ps: the package is `internal` to prevent imports on other projects and with it we dont need to provide support, but i put it on the `platform` package what means that one day it …
=> Moves keyring stuffs to a package to save data locally

cmd/root.go, cmd/version/version.go, go.mod, go.sum
```
Version v1.0.1-23-gfdac727
```
Fixes #231 
@patrick-stephens is this what you had in mind with https://github.com/calyptia/cli/issues/231
If you prefer we can modify this maybe strip Version string and just print out actual tag.
=> Added calyptia version subcommand

cmd/fleet/update_fleet.go, cmd/update.go
Add the missing update command for fleet management.
This is essential for test calyptia/core-fluent-bit#38.
=> fleet: add fleet update command.

cmd/pipeline/config_format.go, cmd/pipeline/config_format_test.go, cmd/pipeline/create_pipeline.go, cmd/pipeline/update_pipeline.go
YAML will be the default in a subsequent release.
For now we keep ini (as default) and enable --config-format to create and update pipeline actions.
```
cli  create pipeline test --config-file config.yaml --core-instance test-config --skip-config-validation --config-format=test
Error: could not create pipeline: invalid pipeline config format
➜ cli (config-format-v2) ✗ ./cli  create pipeline test --config-file config.yaml --core-instance test-config --skip-config-validation --config-format=yaml
ID                                   NAME               AGE
e683e3ad-edc2-4681-bdce-7cdfaa8c6075 game-gauntlet-7d79 Just now
```
then update
```
➜ cli (config-format-v2) ✗ ./cli update pipeline game-gauntlet-7d79 --config-file config.yaml --config-format=yaml
➜ cli (config-format-v2) ✗ ./cli update …
```
=> Allow specifying config format for pipelines.

cmd/coreinstance/create_core_instance_operator.go, cmd/utils/utils.go
If the provided version is latest, use the last released tag instead when
registering the core_instance.
=> [fix] If provided version is latest, use the latest release tag.

cmd/operator/install.go
Allow using namespaces that already exist. I suppose the intent here was to allow creating operators in new namespaces but not in ones we cannot list.
A pretty quick change.
=> install/operator: allow installing to namespaces that already exist.

cmd/root.go
simply change the default --help behavior of showing the current token for a tip about how to get it
eg.
```
Calyptia Cloud CLI
Usage:
calyptia [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
config      Configure Calyptia CLI
create      Create core instances, pipelines, etc.
delete      Delete core instances, pipelines, etc.
get         Display one or many resources
help        Help about any command
install     Install calyptia components
rollout     Rollout resources to previous versions
top         Display metrics
uninstall   Uninstall calyptia components
update      Update core instances, pipelines, etc.
version     Returns currenty Calyptia CLI version.
Flags:
--cloud-url string   Calyptia Cloud URL (default …
```
=> change the --help token message to hide the default token

.gitignore, completer/completer.go
Fixed an error while trying to fetch a fleet given its ID it would try to search it by name first and would error with `invalid fleet name`.
See https://app.asana.com/0/1203043924955727/1205089761290682
=> completer: fix get fleet by id

.goreleaser.yml
Follow suit on https://tip.golang.org/doc/go1.20 and disable CGO entirely (not required) here.
Recompiled and tested with
```
[root@centos-niedbalski jorge]# ldd --version | grep -i libc
ldd (GNU libc) 2.17
[root@centos-niedbalski jorge]# ./calyptia
Calyptia Cloud CLI
Usage:
calyptia [command]
Available Commands:
completion  Generate the autocompletion script for the specified shell
config      Configure Calyptia CLI
create      Create core instances, pipelines, etc.
delete      Delete core instances, pipelines, etc.
get         Display one or many resources
help        Help about any command
install     Install calyptia components
rollout     Rollout resources to previous versions
top         Display metrics
uninstall   Uninstall calyptia components
update      Update core instances, …
```
=> Disable CGO at build time entirely.

cmd/coreinstance/create_core_instance_operator.go, cmd/operator/install.go, cmd/utils/utils.go, k8s/client.go
add to sync deployment metrics_port, as well extended parameters for … core_instance install with --metrics-port
```
--metrics-port string                 Port for metrics endpoint. (default "15334")
```
Important changes:
* `calyptia-core-controller-manager` - operator deployment name has changed for sake of better readability https://github.com/calyptia/core-operator/blob/main/config/default/kustomization.yaml#L4
* versions which were updated by the CI were in incorrect format 1.0.9 vs v1.0.9
=> [Fix] core_instance install 

README.md, cmd/root.go, localdata/keyring.go
Enables CALYPTIA_STORAGE_DIR, if not provided will fallback to $HOME/.calyptia (current default).
If no home is available && no CALYPTIA_STORAGE_DIR its a failure. 
Related to https://app.asana.com/0/1205042382663691/1205181919631508/
=> Fixes user home dir unavailable.

cmd/operator/install.go, cmd/operator/uninstall.go
Force the parameter to be inferred from kube-flags and not from local flags. 
Also note that I will re-instante unit-tests for CLI in a follow-up PR.
N/A.
N/A
=> Use namespace parameter from kube-* flags

cmd/coreinstance/create_core_instance_operator.go
Fetch  clusterName from Kubeconfig and inject it into core instance metadata in Cloud API
https://app.asana.com/0/1205042382663688/1205090901467155/f
For inCluster Kubeconfig currentContext is usually an empty string so in that case to override that i'm injecting value "default"
=> injecting cluster name into core-instance metadata

.github/workflows/ci.yml
Small change to use the old version of e2e testing just to ensure it works for now.
Will be switching to latest with #535 
No change here really, primarily is to unblock any future releases.
=> workflows: switch to non-on-prem version of e2e

cmd/pipeline/update_pipeline.go
Zero is a valid value in the API for replicas count. Allow it (uint).
```
➜ cli (main) ✗ ./cli update pipeline health-check-2e54 --replicas 1
➜ cli (main) ✗ kubectl get pods -A | grep 2e54
default              calyptia-health-check-2e54-fb4c47b66-lkjfp    1/1     Running   0          11m
➜ cli (main) ✗ ./cli update pipeline health-check-2e54 --replicas 0
➜ cli (main) ✗ kubectl get pods -A | grep 2e54
➜ cli (main) ✗
➜ cli (main) ✗
➜ cli (main) ✗
➜ cli (main) ✗ kubectl get pods -A | grep 2e54
```
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1205376078946729
=> Allow updating pipeline to zero replicas.

cmd/coreinstance/update_core_instance_operator.go, cmd/operator/update.go, completer/completer.go, go.mod, go.sum
Check version before allowing CLI to update operator or core-instance 
https://app.asana.com/0/1205296323611471/1205392234116840
This is relying on "github.com/calyptia/core-images-index/go-index" that is reading from https://github.com/calyptia/core-images-index/blob/main/container.index.json which is currently incomplete. 
```
Error: v123 version is not available
```
```
Error: v123 version is not available
```
=> Check version before updating

cmd/pipeline/get_pipeline.go
Allow to specify the config format for pipeline retrieval.
Tested with 
```shell
➜ cli (main) ✗ ./cli get pipeline health-check-c391 --only-config --config-format yaml
service:
HTTP_Server: "On"
HTTP_Listen: 0.0.0.0
HTTP_PORT: 2020
Log_Level: debug
➜ cli (main) ✗ ./cli get pipeline health-check-c391 --only-config --config-format ini
[SERVICE]
HTTP_Server  On
HTTP_Listen  0.0.0.0
HTTP_PORT    2020
Log_Level debug
➜ cli (main) ✗ ./cli get pipeline health-check-c391 --only-config --config-format json
{"service":{"HTTP_Server":"On","HTTP_Listen":"0.0.0.0","HTTP_PORT":2020,"Log_Level":"debug"},"pipeline":{}}
➜ cli (main) ✗ ./cli get pipeline health-check-c391 --only-config
service:
HTTP_Server: "On"
HTTP_Listen: 0.0.0.0
HTTP_PORT: 2020
Log_Level: debug
```
---
- To see the specific tasks where …
=> Enable config formats for pipeline/s retrieval.

cmd/operator/uninstall.go
Fixed uninstall command
https://app.asana.com/0/1204316201844829/1205692588442329/f
Install 
```
$ go run main.go install operator
customresourcedefinition.apiextensions.k8s.io/pipelines.core.calyptia.com created
serviceaccount/calyptia-core-controller-manager created
clusterrole.rbac.authorization.k8s.io/calyptia-core-manager-role created
clusterrole.rbac.authorization.k8s.io/calyptia-core-metrics-reader created
clusterrole.rbac.authorization.k8s.io/calyptia-core-pod-role created
clusterrole.rbac.authorization.k8s.io/calyptia-core-proxy-role created
clusterrolebinding.rbac.authorization.k8s.io/calyptia-core-manager-rolebinding created
clusterrolebinding.rbac.authorization.k8s.io/calyptia-core-proxy-rolebinding created
service/calyptia-core-controller-manager-metrics-service created …
```
=> Fixing uninstall command

cmd/coreinstance/create_core_instance_operator.go, k8s/client.go
This PR adds the http(s)_proxy variables to
create core_instance operator.
```
➜ cli (pass-http-proxy) ✗ ./cli create core_instance operator test --http-proxy=https://localhost:3128    
lenient-jigsaw-9170-sync-to-cloud:
Container ID:   containerd://cd15753a465e1784b2592066406c831d05183bf9818fb63f9b9abc4099b30fcb
Image:          ghcr.io/calyptia/core-operator/sync-to-cloud:v2.0.16
Image ID:       ghcr.io/calyptia/core-operator/sync-to-cloud@sha256:0732e77b2d7afc3e0a465989f7082f6ad36436bf2d107e0a1e5e9dab94c23f8b
Port:           <none>
Host Port:      <none>
State:          Waiting
Reason:       CrashLoopBackOff
Last State:     Terminated
Reason:       Error
Exit Code:    1
Started:      Mon, 23 Oct 2023 17:44:25 +0200
Finished:     Mon, 23 Oct 2023 17:44:25 +0200
Ready:          False …
```
=> Add http_proxy/https_proxy to create core_instance.

cmd/operator/install.go, cmd/operator/update.go
Instead of updating the version of the image
"calyptia update operator" should update the manifest files that will also include the new image versions.
```
➜ cli (main) ✗ calyptia install operator --version v2.0.12   
customresourcedefinition.apiextensions.k8s.io/ingestchecks.core.calyptia.com created
customresourcedefinition.apiextensions.k8s.io/pipelines.core.calyptia.com created
serviceaccount/calyptia-core-controller-manager created
clusterrole.rbac.authorization.k8s.io/calyptia-core-manager-role created
clusterrole.rbac.authorization.k8s.io/calyptia-core-metrics-reader created
clusterrole.rbac.authorization.k8s.io/calyptia-core-pod-role created
clusterrole.rbac.authorization.k8s.io/calyptia-core-proxy-role created
clusterrolebinding.rbac.authorization.k8s.io/calyptia-core-manager-role …
```
=> Switch update to install manifests.

install.sh
Resolves issue with install script when there is a local `calyptia` binary that causes it to fail: this may come about in a myriad of ways including previous failed install script runs.
We remove any local binary prior to attempting to extract it to prevent the failure.
https://app.asana.com/0/1205296321537082/1205915665013499/f
=> install: update to remove old downloaded binary first

cmd/operator/install.go, cmd/operator/update.go
If wait is used, then the extractManifest function gets called, which requires the file to exists.
Remove the defer os.Remove from the install method and move to the main method.
Without this fix.
```
(env) ➜ cloud (main) ✗ calyptia install operator  --wait
Previous operator installation components found:
CustomResourceDefinition Pipeline installed
Operator pod: default/calyptia-core-controller-manager
ClusterRole: calyptia-core-manager-role
ClusterRole: calyptia-core-metrics-reader
ClusterRole: calyptia-core-pod-role
ClusterRole: calyptia-core-proxy-role
ClusterRoleBinding: calyptia-core-manager-rolebinding
ClusterRoleBinding: calyptia-core-proxy-rolebinding
ServiceAccount: default/calyptia-core-controller-manager
Are you sure you want to proceed? (y/N) y …
```
=> Avoid removing manifest file before wait.

cmd/coreinstance/create_core_instance_k8s.go, cmd/coreinstance/create_core_instance_operator.go
Adding debug to help diagnose configuration issues when used by customers and in CI.
e.g. https://github.com/calyptia/core-images/actions/runs/6931739258/job/18855427708#step:8:313 just gives us a generic error with no details on what is configured.
```
```
=> create: add extra info to help debug remotely when creating instances

install.sh
Install script never actually uses the passed in `cli_VERSION` value.
Additionally add support for authentication if provided via `GITHUB_TOKEN`.
Tested via:
```shell
$ export cli_VERSION=1.11.0
$ ./install.sh 
Downloading Calyptia CLI from URL: https://github.com/calyptia/cli/releases/download/v1.11.0/cli_1.11.0_linux_amd64.tar.gz
##################################################################################################################################################################################################### 100.0%
Sudo rights are needed to move the binary to /usr/local/bin, please type your password when asked
Calyptia CLI installed in /usr/local/bin/calyptia
$ calyptia version
1.11.0
$ export cli_VERSION=v1.10.1
$ ./install.sh 
Downloading Calyptia CLI from URL: …
```
=> install: ensure we actually use the passed in version

cmd/operator/install.go, cmd/operator/uninstall.go, k8s/client.go
When uninstall operator is invoked all pipelines, ingestchecks and other potential leftoves will be wiped from the cluster.
Loosely related to this: 
https://app.asana.com/0/1204316201844829/1206045382355812
You will notice that ClusterRoles, ClusterRoleBindings and ServiceAccount are being removed too. This is because that when the first pipeline is created we create those to ensure that pipelines have minimum required permissions to work in the cluster. https://github.com/calyptia/core-operator/blob/main/pkg/provider/pipeline.go#L466
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
- https://app.asana.com/0/0/1206179313345498
=> ensure that all calyptia objects are removed from the cluster

k8s/client.go
Fixes two consecutive core instance update issue causes wait to fail removing annotation patch function and integrate it before the update
=> fix: two consecutive core instance update issue

k8s/client.go
Update after Chronosphere migration for new location.
=> migration: update repo location for operator releases

.goreleaser.yml
chore: removes calyptia_cli_bucket GCS usage
https://app.shortcut.com/chronosphere/story/80912/gcp-confirm-gcs-is-required-and-which
=> chore: remove calyptia_cli_bucket GCS usage

.github/workflows/ci.yml, install.sh
Resolve issues with release process and dep updates for actions.
Fixes install script failure with old name.
```
...
curl -sSfL https://raw.githubusercontent.com/anchore/syft/main/install.sh | sh -s -- -b /usr/local/bin
[info] fetching release script for tag='v0.105.0' 
[info] using release tag='v0.105.0' version='0.105.0' os='linux' arch='amd64' 
install: cannot create regular file '/usr/local/bin/syft': Permission denied
Error:  failed to install syft 
...
• DEPRECATED: --skip-validate was deprecated in favor of --skip=validate, check https://goreleaser.com/deprecations#-skip for more details
```
=> workflows: dep updates and Syft install

.goreleaser.yml
Migration of Homebrew-tap to new location.
Removed GCS usage as all handled by Github Releases.
=> Update .goreleaser.yml for new repo location

cmd/operator/install.go, cmd/operator/install_test.go, cmd/operator/manifest.yaml, cmd/operator/update.go
Simplified version of #781 to reduce the impact, I agree we should have better YAML handling but not sure we should also do all that in a single PR. This tries to follow the existing simple string replacement approach.
No need to expose this to helm charts, it is only required for the package installation on K3S.
=> [sc-84760]: add local traffic policy option to CLI

cmd/operator/install.go, cmd/operator/update.go
Incorrect operator arguments mean it is not setting the right traffic policy and blocking https://github.com/chronosphereio/calyptia-core-packages/pull/333
Also fixed missing update inclusion and added basic logging of this feature being enabled.
Raised a separate improvement story on logging to help with future updates.
=> [sc-86134]: fix operator args

cmd/operator/manifest.yaml
Auto update PR inadvertently removed args support which breaks source-ip injection for K3S packages: https://github.com/chronosphereio/calyptia-cli/pull/798/files
We need to push a release up to resolve issues found in tests here: https://github.com/chronosphereio/calyptia-core-packages/pull/335
=> Revert removal of args support

.github/workflows/ci.yml, .goreleaser.yml, install.sh
Releases are currently building containers twice which takes an age for the ARM ones on an AMD host so removed that.
No GCP access required anymore (used to push to a bucket) so removed that.
Running the GoReleaser step on all CI but with configurable flags, this will verify it prior to release then as well.
Update GoReleaser config to correctly handle universal binaries and also add some extra info for the brew recipe.
Added Windows ARM 64 build as well.
Updated install script to support more options and cope with non-zero root users or similar sudo stuff.
=> Optimise and update CI

cmd/coreinstance/create_core_instance_operator.go, cmd/coreinstance/update_core_instance_operator.go, k8s/client.go, k8s/client_test.go
passing skip-service-creation into sync
[sc-92924](https://app.shortcut.com/chronosphere/story/92924/ability-to-set-a-static-service-name-for-a-pipeline-in-calyptia)
```
~/calyptia-cli# calyptia create core_instance operator --name test --skip-service-creation
Found calyptia core operator installed, version: v2.12.0...
Core instance created successfully
Deployed images=(sync-to-cloud: ghcr.io/calyptia/core-operator/sync-to-cloud:v2.12.0, sync-from-cloud: ghcr.io/calyptia/core-operator/sync-from-cloud:v2.12.0)
Resources created:
Deployment=calyptia-test-default-sync
Secret=calyptia-test-default-secret
ClusterRole=calyptia-test-default-cluster-role
ClusterRoleBinding=calyptia-test-default-cluster-role-binding
ServiceAccount=calyptia-test-default-service-account
~/calyptia-cli# kubectl get …
```
=> passing skip-service-creation into sync

install.sh
Missing URL usage for new macOS single binary install.
Tested locally on macOS:
```
$ ./install.sh 
Downloading from URL:  https://github.com/chronosphereio/calyptia-cli/releases/download/v1.19.0/calyptia-cli_1.19.0_darwin_all.tar.gz
######################################################################################################################################################################################################################## 100.0%
Sudo rights are needed to move the binary to /usr/local/bin, please type your password when asked
Password:
Calyptia CLI installed in /usr/local/bin
$ calyptia version
1.19.0
```
Tested on centos container:
```
$ docker run --rm -it -v ./install.sh:/install.sh:ro centos 
Unable to find image 'centos:latest' locally
latest: Pulling from …
```
=> Fix macOS download

cmd/coreinstance/create_core_instance_operator.go, cmd/coreinstance/update_core_instance_operator.go, cmd/operator/update.go, k8s/client.go, k8s/client_test.go
adding no-proxy, http-proxy and https-proxy to CLI core_instance update
[sc-93807](https://app.shortcut.com/chronosphere/story/93807/cli-update-http-proxy-https-proxy-and-no-proxy)
[sc-93976](https://app.shortcut.com/chronosphere/story/93976/ability-to-configure-proxy-for-both-inbound-and-outbound-traffic)
=> adding no-proxy, http-proxy and https-proxy to CLI core_instance update

cmd/operator/manifest.yaml, cmd/utils/utils.go
for some reason previous operator release didn't bump versions accordingly so I'm doing it manually
=> bumping to 2.12.8
